version: '3'
services:
  mongodb:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
  redis:
    image: redis:6.2.6-alpine
    ports:
      - '${REDIS_HOST}:${REDIS_PORT}:6379/tcp'
