name: build
on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'packages/**/*.ts'
      - 'package-lock.json'
    types:
      - closed
      - opened
      - reopened
      - synchronize
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!(github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false)"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install cuaklabs dependencies
        run: npm run build:ci

      - name: Lint source files
        run: npm run lint

      - name: Compile source files
        run: npm run build:ci:test

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "::set-output name=gitCommitHash::$(git rev-parse HEAD)"

      - uses: actions/cache@v2
        id: ts-build-cache
        with:
          path: |
            ./packages
          key: ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}
          restore-keys: |
            ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}

  test-coverage-package:
    name: Test with coverage
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - env
          - redis
          - test-utils
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "::set-output name=gitCommitHash::$(git rev-parse HEAD)"

      - uses: actions/cache@v2
        id: ts-build-cache
        with:
          path: |
            ./packages
          key: ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}
          restore-keys: |
            ts-build-${{ steps.get-git-commit-hash.outputs.gitCommitHash }}

      - name: Build on cache miss
        run: npm run build
        if: ${{ !steps.ts-build-cache.outputs.cache-hit }}

      - name: Link packages
        run: npm run packages:link

      - name: Launch docker images
        run: npm run docker:up:test:ci

      - name: Launch Tests and generate coverage report
        run: npm run test:package:${{ matrix.package }}:js:ci:coverage

      - name: Upload coverage to Codecov (base branch)
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.package }}
          override_branch: ${{ github.base_ref }}
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}

      - name: Upload coverage to Codecov (branch)
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.package }}
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ !(github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}

  test-coverage:
    name: Test with coverage
    needs: test-coverage-package
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Done!"'
